name: ci

on:
  push:
    branches:
      - 'trunk'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 2.7.5
        uses: docker/build-push-action@v2
        with:
          context: ./2-7-5/alpine/.
          push: true
          tags: harisr/ruby-node:2-7-5alpine harisr/ruby-node:latest
